# Generated by Django 4.2.1 on 2023-06-02 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 15, 58, 13, 939330, tzinfo=datetime.timezone.utc)),
        ),
    ]
