# Generated by Django 4.2.1 on 2023-06-03 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 2, 31, 18, 270146, tzinfo=datetime.timezone.utc)),
        ),
    ]
