# Generated by Django 4.2.1 on 2023-06-06 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 15, 5, 28, 941260, tzinfo=datetime.timezone.utc)),
        ),
    ]
